### ISSUE TITLE
Dynamically assign camera to context menu

### ISSUE THREAD

**Issue by LatteG** [LatteG/DATX02-19-11#14]
Now the context menu needs to have the Event Camera manually assigned to it in the scene. This is impractical, especially if we want to be able to spawn objects with context menus.

This might be solvable by only assigning the Event Camera once a player wants to open the menu, and then assigning that player's camera as the Event Camera. If the object is a player figurine it might be a good idea to check if the player owns that figurine as well.

**Comment by guseismjo** [comment]
I fixed this for the canvas on player figurines (for the buttons popping up when pressing a figurine). Not sure if that's what this issue is about.
